@extends('layouts.app')

@section('title', 'Reports')
@section('page-title', 'Reports')

@section('content')

{{-- MAIN REPORTS TABLE CARD --}}
<div class="bg-white rounded-2xl border border-slate-100 shadow-sm overflow-hidden mt-2">

    <div class="p-6 border-b border-slate-100 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
            <h2 class="font-bold text-slate-800">Generated Reports</h2>
        </div>

        <button class="w-full sm:w-auto inline-flex items-center justify-center gap-1.5 text-sm font-semibold text-slate-600 hover:text-emerald-600 transition px-3 py-2 sm:py-1.5 rounded-xl sm:rounded-lg bg-slate-50 sm:bg-transparent hover:bg-slate-100/70 cursor-pointer">
            <i class="ti ti-download text-base"></i>
            Export Master Log
        </button>
    </div>

    <div class="hidden md:block overflow-x-auto">
        <table class="w-full text-sm">
            <thead class="bg-gray-50">
                <tr class="text-left text-gray-500 text-xs font-semibold uppercase tracking-wider">
                    <th class="px-6 py-4">Type</th>
                    <th class="px-6 py-4">Generated By</th>
                    <th class="px-6 py-4">Records</th>
                    <th class="px-6 py-4">Date</th>
                    <th class="px-6 py-4 text-right">Actions</th>
                </tr>
            </thead>

            <tbody class="divide-y divide-slate-100">
                @forelse($reports as $report)
                    <tr class="hover:bg-gray-50/50 transition">
                        <td class="px-6 py-4">
                            <span class="px-2.5 py-1 text-xs font-semibold rounded-lg bg-slate-100 border border-slate-200 text-slate-700">
                                {{ ucfirst($report->type) }}
                            </span>
                        </td>

                        <td class="px-6 py-4 font-medium text-slate-800">
                            {{ $report->generator->name ?? 'System' }}
                        </td>

                        <td class="px-6 py-4 text-slate-600 font-mono text-xs">
                            {{ number_format($report->total_records) }} rows
                        </td>

                        <td class="px-6 py-4 text-slate-600">
                            {{ optional($report->generated_at)->format('M d, Y') }}
                        </td>

                        <td class="px-6 py-4 text-right whitespace-nowrap">
                            <a href="{{ route('reports.show', $report) }}" class="inline-flex items-center gap-1 font-semibold text-emerald-600 hover:text-emerald-700 transition">
                                View <i class="ti ti-chevron-right text-xs"></i>
                            </a>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="5" class="px-6 py-16 text-center text-gray-400">
                            <div class="flex flex-col items-center justify-center space-y-2">
                                <i class="ti ti-report-off text-4xl text-gray-300"></i>
                                <span class="text-sm">No reports generated yet.</span>
                            </div>
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="block md:hidden divide-y divide-slate-100">
        @forelse($reports as $report)
            <div class="p-4 space-y-3.5">
                <div class="flex items-start justify-between gap-3">
                    <div>
                        <span class="inline-block px-2.5 py-0.5 text-xs font-semibold rounded-lg bg-slate-100 border border-slate-200 text-slate-700">
                            {{ ucfirst($report->type) }}
                        </span>
                        <div class="font-medium text-slate-800 text-sm mt-2">
                            <span class="text-xs text-slate-400 block font-normal uppercase tracking-wider mb-0.5">Generated By</span>
                            {{ $report->generator->name ?? 'System' }}
                        </div>
                    </div>

                    <div class="text-right">
                        <span class="text-[10px] uppercase font-bold tracking-wider text-slate-400 block">Date</span>
                        <span class="text-xs text-slate-600 font-medium block mt-1">
                            {{ optional($report->generated_at)->format('M d, Y') }}
                        </span>
                    </div>
                </div>

                <div class="flex items-center justify-between gap-2 bg-slate-50/60 rounded-xl p-3 border border-slate-100/80 text-xs">
                    <div>
                        <span class="text-slate-400">Data Volume:</span>
                        <span class="font-mono font-bold text-slate-700 ml-1">{{ number_format($report->total_records) }} rows</span>
                    </div>
                </div>

                <div class="pt-1">
                    <a href="{{ route('reports.show', $report) }}" class="w-full inline-flex items-center justify-center gap-1.5 bg-slate-50 hover:bg-slate-100 border border-slate-200 text-slate-700 py-2 rounded-xl text-xs font-semibold transition">
                        View Report Details <i class="ti ti-chevron-right text-xs text-slate-400"></i>
                    </a>
                </div>
            </div>
        @empty
            <div class="px-6 py-16 text-center text-gray-400">
                <div class="flex flex-col items-center justify-center space-y-2">
                    <i class="ti ti-report-off text-4xl text-gray-300"></i>
                    <span class="text-sm">No reports generated yet.</span>
                </div>
            </div>
        @endforelse
    </div>

    @if(method_exists($reports, 'hasPages') && $reports->hasPages())
        <div class="p-4 border-t border-slate-100 bg-slate-50/50">
            {{ $reports->links() }}
        </div>
    @endif
</div>

@endsection
