@extends('layouts.app')

@section('title', 'Reports')
@section('page-title', 'Reports')

@section('content')

{{-- MAIN REPORTS TABLE CARD --}}
<div class="bg-white rounded-2xl border border-slate-100 shadow-sm overflow-hidden mt-2">

    <div class="p-6 border-b border-slate-100 flex items-center justify-between">
        <div>
            <h2 class="font-bold text-slate-800">Generated Reports</h2>
            <p class="text-xs text-slate-500 mt-0.5">View and download structural operational data summaries</p>
        </div>

        <button class="inline-flex items-center gap-1.5 text-sm font-semibold text-slate-600 hover:text-emerald-600 transition px-3 py-1.5 rounded-lg hover:bg-slate-50 cursor-pointer">
            <i class="ti ti-download text-base"></i>
            Export Master Log
        </button>
    </div>

    <div class="overflow-x-auto">
        <table class="w-full min-w-[840px] text-sm">
            <thead class="bg-gray-50">
                <tr class="text-left text-gray-500 text-xs font-semibold uppercase tracking-wider">
                    <th class="px-6 py-4">Type</th>
                    <th class="px-6 py-4">Generated By</th>
                    <th class="px-6 py-4">Records</th>
                    <th class="px-6 py-4">Date</th>
                    <th class="px-6 py-4 text-right">Actions</th>
                </tr>
            </thead>

            <tbody class="divide-y divide-slate-100">
                @forelse($reports as $report)
                    <tr class="hover:bg-gray-50/50 transition">
                        <td class="px-6 py-4">
                            <span class="px-2.5 py-1 text-xs font-semibold rounded-lg bg-slate-100 border border-slate-200 text-slate-700">
                                {{ ucfirst($report->type) }}
                            </span>
                        </td>

                        <td class="px-6 py-4 font-medium text-slate-800">
                            {{ $report->generator->name ?? 'System' }}
                        </td>

                        <td class="px-6 py-4 text-slate-600 font-mono text-xs">
                            {{ number_format($report->total_records) }} rows
                        </td>

                        <td class="px-6 py-4 text-slate-600">
                            {{ optional($report->generated_at)->format('M d, Y') }}
                        </td>

                        <td class="px-6 py-4 text-right whitespace-nowrap">
                            <a href="{{ route('reports.show', $report) }}" class="inline-flex items-center gap-1 font-semibold text-emerald-600 hover:text-emerald-700 transition">
                                View <i class="ti ti-chevron-right text-xs"></i>
                            </a>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="5" class="px-6 py-16 text-center text-gray-400">
                            <div class="flex flex-col items-center justify-center space-y-2">
                                <i class="ti ti-report-off text-4xl text-gray-300"></i>
                                <span class="text-sm">No reports generated yet.</span>
                            </div>
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    @if(method_exists($reports, 'hasPages') && $reports->hasPages())
        <div class="p-4 border-t border-slate-100 bg-slate-50/50">
            {{ $reports->links() }}
        </div>
    @endif
</div>

@endsection
