@extends('layouts.app')

@section('title', 'Report Details')
@section('page-title', 'Report Details')

@section('content')

<div class="max-w-3xl">
    <div class="mb-6">
        <h1 class="text-2xl lg:text-3xl font-bold text-gray-800">Report Details</h1>
        <p class="text-sm text-gray-500 mt-1">View the selected report metadata</p>
    </div>

    <x-card>
        <div class="p-6 space-y-6">
            <div class="grid gap-4 md:grid-cols-2">
                <div>
                    <span class="text-sm text-slate-500">Report Type</span>
                    <p class="mt-1 font-semibold text-gray-900">{{ ucfirst($report->type) }}</p>
                </div>
                <div>
                    <span class="text-sm text-slate-500">Generated By</span>
                    <p class="mt-1 font-semibold text-gray-900">{{ $report->generator->name ?? 'System' }}</p>
                </div>
                <div>
                    <span class="text-sm text-slate-500">Generated At</span>
                    <p class="mt-1 font-semibold text-gray-900">{{ optional($report->generated_at)->format('F d, Y H:i') }}</p>
                </div>
                <div>
                    <span class="text-sm text-slate-500">Total Records</span>
                    <p class="mt-1 font-semibold text-gray-900">{{ $report->total_records }}</p>
                </div>
            </div>

            <div>
                <span class="text-sm text-slate-500">Report Meta</span>
                <pre class="mt-2 rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm text-slate-700 overflow-x-auto">{{ $report->meta }}</pre>
            </div>

            <div class="flex items-center gap-3">
                <a href="{{ route('reports.index') }}" class="btn">Back to reports</a>
            </div>
        </div>
    </x-card>
</div>

@endsection
